name: Bundle for release

on:
  release:
    types:
      - published

jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly
      - name: Bundle this library into .tar.br and upload it to latest release's assets
        uses: hasnep/bundle-roc-library@v0.1.0
        with:
          library: package/main.roc
          token: ${{ github.token }}

